build:
    environment:
        docker: true          
    tests:
      override:
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javac HelloWorld.java
          - command: ls -la
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 java HelloWorld
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javap HelloWorld
            on_node: 1 
